### ISSUE TITLE
TimVer 0.8.5 - Installer issue

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/TimVer#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened or didn't happen

@Timthreetwelve m

The accented letters are now sown right.

Please check screenshot.

![image](https://github.com/Timthreetwelve/TimVer/assets/1262554/f5604e28-6a78-478d-8a04-d709f7d72544)

You have two instalerl (x64 and x64).
I beleive that is important show in window caption version and platform for the installer.

I bleieve that it's important toi add the info about requirement in otehr place and dsiable first window.
In this way it's possible toi add version/platform on window caption on top left.

**No automatic language detect**

At first run teh progranm didn't detect OS langauge and start always in English.
I propsoe you to detect at first run detection of OS language and set program language.

**GUI Issues**

![image](https://github.com/Timthreetwelve/TimVer/assets/1262554/bd7ff5ca-34e4-43e1-b8ef-c08814ac73c8)

GUI require a scroll on right.
Please increase right panel width

![image](https://github.com/Timthreetwelve/TimVer/assets/1262554/ff890d3d-b5b3-4bc8-83a3-c0588637f902)

GUI require a scroll on bottom and right.
Please increase right panel width/height

I beleiev that coukld be better to set by default a right panel with more height/width 

![image](https://github.com/Timthreetwelve/TimVer/assets/1262554/058888e1-9cc0-4a66-918b-6a2336438b73)

What's "Videcontroller1"?

### Steps To Reproduce

Run the installer

### Version

0.8.5

### Windows Version

Windows 10 22 H2 64 bit italian

**Comment by Timthreetwelve** [comment]
@bovirus 

To address the size issues, I've updated the minimum window size and the default size when first installed. After the first run the app remembers it's size. 

To address the installer issues, I made several changes.

The improperly displayed characters we due to file encoding. 🤦🏻

In TimVerLocaization.iss, in the [Messages] section, the custom messages for WelcomeLabel2 were removed.  

Three new messages per language in the [CustomMessages] section have been added. There are three to allow customization for each of the three types of installation. These messages effectively replace the WelcomeLabel2 messages. 

In TimVerEx.iss a new InitializeWizard procedure was added to the [Code] section. This procedure will use the InstallType constant, that is created during the publishing process, to insert the proper message back into WelcomeLabel2.

Finally, in TimVerLocalization.iss [Messages] section, new messages were added to put the version number into the installer windows title bar. 

If you would, please verify the [Messages] section and add the appropriate translations to the [CustomMessages] section. 

Screenshots showing different messages based on installer type.

![TimVer_0 8 6 8_SC_x64_Setup tmp_2024-01-10_19-54-19](https://github.com/Timthreetwelve/TimVer/assets/43152358/f33ccae7-4494-4c6c-a133-8f1514ddc63a)

![TimVer_0 8 6 8_x64x86_Setup tmp_2024-01-10_19-51-43](https://github.com/Timthreetwelve/TimVer/assets/43152358/5e9c5567-8955-4d67-a9af-d54891ac115c)

If the installer changes don't have any issues, I will bring them over to WUView, GetMyIP, etc.

FYI, this weekend is my mother's 100th birthday!🎉 I will be busy with out-of-town family and won't be able to spend much time on my projects.

Tim

**Comment by Timthreetwelve** [comment]
And "VideoController1" is the system assigned device ID.

**Comment by bovirus** [comment]
@Timthreetwelve 

I updated the instalelr sstring for italian.
I change the order of spanish string to copy the order of english strings.

I porpose to change string like

click xxx 

in 

click 'xxx' 

to highlight that you should select a button.

Thanks.

**Comment by Timthreetwelve** [comment]
Version 0.8.100 has been released with fixes.

Thanks,
Tim
